version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: scmlearning/batch9image:1.0
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: always
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:
